import { Restaurant } from '../models/Restaurant';

export const RESTAURANTS: Restaurant[] = [
  {
    id: 1,
    name: 'Alla Mafia',
    price_category: 1,
    rating: 1,
    type: 'italienisch',
    number_of_reviews: 1,
    distance: 1,
  },
  {
    id: 2,
    name: 'El toro',
    price_category: 2,
    rating: 2,
    type: 'spanisch',
    number_of_reviews: 2,
    distance: 2,
  },
  {
    id: 3,
    name: 'Pizza Hut',
    price_category: 3,
    rating: 3,
    type: 'pizza',
    number_of_reviews: 3,
    distance: 3.5,
  },
  {
    id: 4,
    name: 'KFC',
    price_category: 4,
    rating: 4,
    type: 'asiatisch',
    number_of_reviews: 3,
    distance: 4,
  },
  {
    id: 5,
    name: 'McDonalds',
    price_category: 3,
    rating: 5,
    type: 'asiatisch',
    number_of_reviews: 5,
    distance: 5,
  },
  {
    id: 6,
    name: 'Burger King',
    price_category: 2,
    rating: 3,
    type: 'asiatisch',
    number_of_reviews: 6,
    distance: 6,
  },
  {
    id: 7,
    name: 'Pizza Hut',
    price_category: 5,
    rating: 4,
    type: 'pizza',
    number_of_reviews: 7,
    distance: 7,
  },
  {
    id: 8,
    name: 'KFC',
    price_category: 2,
    rating: 2,
    type: 'asiatisch',
    number_of_reviews: 8,
    distance: 8,
  },
  {
    id: 9,
    name: 'McDonalds',
    price_category: 3,
    rating: 1,
    type: 'asiatisch',
    number_of_reviews: 9,
    distance: 9,
  },
  {
    id: 10,
    name: 'Burger King',
    price_category: 4,
    rating: 5,
    type: 'asiatisch',
    number_of_reviews: 10,
    distance: 10,
  },
];
